// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_primary.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: PrimaryFirebaseOptions.currentPlatform,
/// );
/// ```
class PrimaryFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'PrimaryFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'PrimaryFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'PrimaryFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'PrimaryFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'PrimaryFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALJupmnVb8br2ZuKOVlAJ8MqiqrFb6SlI',
    appId: '1:964996831108:android:6294af9309062c8a55efd1',
    messagingSenderId: '964996831108',
    projectId: 'feetrack-all-service',
    storageBucket: 'feetrack-all-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyb0SFJ1w4vyHcWrs3C45l-WAXt0n5GIo',
    appId: '1:964996831108:ios:d17fbe2f632912d455efd1',
    messagingSenderId: '964996831108',
    projectId: 'feetrack-all-service',
    storageBucket: 'feetrack-all-service.firebasestorage.app',
    iosBundleId: 'com.feetrack.gym.room.tpipay',
  );
}
