// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_secondary.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsSecond.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsSecond {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptionsSecond have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptionsSecond have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptionsSecond have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsSecond have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsSecond are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeBj2IvMd1WhTEyb7Daf7hj7BsKID259w',
    appId: '1:252507782720:android:8953e98786febdbc2fe9a5',
    messagingSenderId: '252507782720',
    projectId: 'chat-app-9a664',
    storageBucket: 'chat-app-9a664.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0k0hIDyVh_GY4DaTRH4Z2o0HaBGvY3_g',
    appId: '1:252507782720:ios:830549f201fcd4a42fe9a5',
    messagingSenderId: '252507782720',
    projectId: 'chat-app-9a664',
    storageBucket: 'chat-app-9a664.firebasestorage.app',
    androidClientId: '252507782720-fqg5ua56seqnbmnt8gmni05trl11928n.apps.googleusercontent.com',
    iosClientId: '252507782720-72oe1s1rm6boqngnd4le17h6r58n6o9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.feetrackGymRoom',
  );
}
