// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4PAuEsCFKp55h2ZDeUqnrjJz_BZ_cOoQ',
    appId: '1:271741735160:web:6eb616063a090aa4f62b0d',
    messagingSenderId: '271741735160',
    projectId: 'feetrack-bb7af',
    authDomain: 'feetrack-bb7af.firebaseapp.com',
    storageBucket: 'feetrack-bb7af.firebasestorage.app',
    measurementId: 'G-6NBCZQXND1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIVDe3olvCo6xVk24NxZ8AXXPceqvhARk',
    appId: '1:271741735160:android:b7b349f59c28e8c3f62b0d',
    messagingSenderId: '271741735160',
    projectId: 'feetrack-bb7af',
    storageBucket: 'feetrack-bb7af.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6TIXJXewPgR0Qac9wBdwMzT1NE7y1Qpo',
    appId: '1:271741735160:ios:d664d271e8399294f62b0d',
    messagingSenderId: '271741735160',
    projectId: 'feetrack-bb7af',
    storageBucket: 'feetrack-bb7af.firebasestorage.app',
    iosBundleId: 'com.feetrack.gym.room.tpipay',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6TIXJXewPgR0Qac9wBdwMzT1NE7y1Qpo',
    appId: '1:271741735160:ios:d664d271e8399294f62b0d',
    messagingSenderId: '271741735160',
    projectId: 'feetrack-bb7af',
    storageBucket: 'feetrack-bb7af.firebasestorage.app',
    iosBundleId: 'com.feetrack.gym.room.tpipay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4PAuEsCFKp55h2ZDeUqnrjJz_BZ_cOoQ',
    appId: '1:271741735160:web:6eb616063a090aa4f62b0d',
    messagingSenderId: '271741735160',
    projectId: 'feetrack-bb7af',
    authDomain: 'feetrack-bb7af.firebaseapp.com',
    storageBucket: 'feetrack-bb7af.firebasestorage.app',
    measurementId: 'G-6NBCZQXND1',
  );
}
